### PR TITLE
Add berkeley computational resources

### PR DESCRIPTION
**Pull request by choldgraf**
Hey - this is a small addition to the resources page.  It adds a short list of berkeley-specific resources that might be of interest to people currently residing here.  It is largely inspired by how common I send "you should check all of these things out" e-mails to people I talk to about data science, or to classes (e.g., SC bootcamps) that I teach.  

The list is by no means complete, and mostly meant to be a first step in eventually having a more complete and fleshed out list. 

Also note that this is also an experiment for me in forking.  Apologies if I messed something up but this is the first time I've worked with the "fork and pull" github method.

### CODE REVIEW

**Comment by davclark** [comment]
Hey Chris, it's awesome to have you contributing to the resource - pushing it more in the genuine "community resource" direction.

You appear to have merged the master branch into gh-pages. I'm open to restructuring the site, but if we are moving stuff from master, we should also remove it so it doesn't exist in two places (and update the relevant links).

You also mentioned this was your first time messing with branches on GitHub, so I don't know if this was intentional on your part.

So, let me know what you're intending, and we'll shape things up somehow - happy to work with you in person on this one to make sure we're on the same page.

**Comment by choldgraf** [comment]
Hey - totally unintentional.  Mind if we meet up sometime soon and you can run me through it?

**Comment by davclark** [comment]
We talked about this ages ago - but I'm not sure it ever got resubmitted...

**Comment by choldgraf** [comment]
Ah, do you want me to open a new PR?

**Comment by davclark** [comment]
Only if you'd like. I thought you wanted to so you could practice your git!

**Comment by choldgraf** [comment]
OK, will do! I got some practice with the Bootcamp do hopefully this will
work OK :-)

**Pull request closed without merging**
